# Change these first
owner: Manubi # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Impfi
    url: https://www.impfi.at
assignees: # Users to assign downtime issues (optional)
  - Manubi

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: upptime.impfi.at
  name: Upptime
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
